- name: configuring mongodb using ansible
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
      remote_src: yes
  - name: install mongodb
    ansible.builtin.command: " dnf install mongodb-org -y"
  
