- name: configure user
  hosts: user
  become: yes
  tasks:
  - name: disable nodejs module
    ansible.builtin.command: "dnf module disable nodejs -y"
  - name: enable nodejs module
    ansible.builtin.command: "dnf module enable nodejs:20 -y"
  - name: install  nodejs 
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: crete system user 
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true # system user creation

  - name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download application code for user
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
  
  - name: unzip application code for user
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: true
  
  - name: install nodejs dependencies
    community.general.npm:
      path: /app
  
  - name: copy user service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon_reload user service
    ansible.builtin.systemd:
      daemon_reload: true

  - name: enable and start user service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes


      